CREATE DATABASE IF NOT EXISTS mechanic_db;
USE mechanic_db;

DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS spare_parts;
DROP TABLE IF EXISTS spare_parts_types;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(45) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_admin TINYINT(1) DEFAULT 0,
    status CHAR(1) NOT NULL DEFAULT 'A',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE services (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL UNIQUE,
    image VARCHAR(255) NULL, 
    status CHAR(1) NOT NULL DEFAULT 'A',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE spare_parts_types (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL UNIQUE,
    status CHAR(1) NOT NULL DEFAULT 'A',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE spare_parts (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    type_id INT NOT NULL,
    name VARCHAR(45) NOT NULL,
    brand_name VARCHAR(25) NOT NULL,
    image VARCHAR(255) NULL,
    description TEXT NULL, 
    status CHAR(1) NOT NULL DEFAULT 'A',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (type_id) REFERENCES spare_parts_types(id) ON DELETE CASCADE
);

CREATE TABLE appointments (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    customer_name VARCHAR(100) NOT NULL, 
	phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    brand VARCHAR(25) NOT NULL,
    model VARCHAR(45) NOT NULL,
    vehicle_year YEAR NOT NULL, 
    license_plate VARCHAR(15) NOT NULL, 
    mileage INT UNSIGNED NOT NULL,
    service_id INT NOT NULL,
    comment TEXT NULL,
    token VARCHAR(64) NOT NULL,
    token_used TINYINT(1) DEFAULT 0,
    appointment_status ENUM('P', 'A', 'R', 'F') DEFAULT 'P', 
	appointment_date DATETIME NULL,
	
    status CHAR(1) NOT NULL DEFAULT 'E',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (token),
    FOREIGN KEY (service_id) REFERENCES services(id)
);
